spring.application.name=backend

# Server Port Configuration
server.port=${PORT:8080}

# MongoDB Atlas Connection
spring.data.mongodb.database=studysync

# Allow cross-origin requests during testing
spring.web.resources.add-mappings=true