spring.application.name=backend
server.port=${PORT:8080}

# Explicitly force Spring Boot to look for the cloud environment variable
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.data.mongodb.database=studysync

spring.web.resources.add-mappings=true